name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda/**"  # Only trigger if code in lambda/ changes

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js (optional, only if your Lambda uses Node dependencies)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # change to your Node runtime

      # 3. Install dependencies (if you have package.json)
      - name: Install dependencies
        working-directory: lambda
        run: |
          if [ -f package.json ]; then
            npm install --production
          fi

      # 4. Zip Lambda code
      - name: Zip Lambda code
        working-directory: lambda
        run: zip -r ../lambda.zip . -x "*.git*" "*.DS_Store"

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6. Update Lambda function
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name lunebi-prod-us-east-1-lambda \
            --zip-file fileb://lambda.zip \
            --publish

