name: Terraform Pipeline

on:
  workflow_dispatch: # run manually from GitHub Actions tab
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [us-east-1] # add eu-central-1 later

    defaults:
      run:
        working-directory: infra/envs/${{ matrix.region }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (US)
        if: matrix.region == 'us-east-1'
        env:
           TF_VAR_signed_url_public_key: ${{ secrets.PUBLIC_KEY }}
        run: terraform plan 

      - name: Terraform Apply (US)
        if: matrix.region == 'us-east-1'
        env:
          TF_VAR_signed_url_public_key: ${{ secrets.PUBLIC_KEY }}
        run: terraform apply -auto-approve 

      # --- Disabled EU jobs for now ---
      # - name: Terraform Plan (EU)
      #   if: matrix.region == 'eu-central-1'
      #   run: terraform plan -out=tfplan
      #
      # - name: Terraform Apply (EU)
      #   if: matrix.region == 'eu-central-1'
      #   run: terraform apply -auto-approve tfplan
