name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: ["infra/**"]

env:
  TF_VERSION: "1.9.8"

jobs:
  terraform-plan-us:
    name: "Plan - US East 1"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/envs/us-east-1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform plan
        env:
          TF_VAR_signed_url_public_key: ${{ secrets.PUBLIC_KEY }}

  terraform-apply-us:
    name: "Apply - US East 1"
    runs-on: ubuntu-latest
    needs: [terraform-plan-us]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://api.lunebi.com
    defaults:
      run:
        working-directory: infra/envs/us-east-1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform apply -auto-approve

        env:
          TF_VAR_signed_url_public_key: ${{ secrets.PUBLIC_KEY }}